const postsActionTypes = {
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POST_SUCCESS: "GET_POST_SUCCESS",
  POST_ERROR: "POST_ERROR",
  UPDATE_LIKES : "UPDATE_LIKES",
  DELETE_POST: "DELETE_POST",
  ADD_POST: "ADD_POST",
  CLEAR_POST: "CLEAR_POST"
}

export default postsActionTypes;