const profileActionTypes = {
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILED: "GET_PROFILE_FAILED",
  CLEAR_PROFILE: "CLEAR_PROFILE"
}

export default profileActionTypes;