const profileActionTypes = {
  FETCH_START: "FETCH_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_ALL_PROFILES_SUCCESS: "GET_ALL_PROFILES_SUCCESS",
  GET_GITHUB_REPOS_SUCCESS: "GET_GITHUB_REPOS_SUCCESS",
  PROFILE_ERROR: "PROFILE_ERROR",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  CLEAR_PROFILE: "CLEAR_PROFILE"
}

export default profileActionTypes;