const profileActionTypes = {
  GET_PROFILE_START: "GET_PROFILE_START",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  PROFILE_ERROR: "PROFILE_ERROR",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  CLEAR_PROFILE: "CLEAR_PROFILE"
}

export default profileActionTypes;